services:
  db:
    image: postgres:17.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '2503:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local